# Generated by Django 4.0 on 2021-12-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_user_comment_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
    ]
