# Generated by Django 4.0 on 2022-02-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_ad_created_at_alter_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
